### PR TITLE
Properly integrating types and methods of surface model

### LINKED ISSUE #15: Code generation for OpenAPI v3 doesn't seem to work at all
From the examples:
```
$ gnostic bookstore.json --go-generator-out=bookstore
Errors reading bookstore.json
Plugin error: [types.go:31:12: expected ';', found '/' (and 10 more errors)]
Plugin error: [types.go:31:12: expected ';', found '/' (and 10 more errors)]
```

Doesn't seem to work for any other openapi v3 definitions I have on hand.

### PR DESCRIPTION
**Pull request by LorenzHW**
Fixes #15 

This PR adjusts this plugin to the types and methods received from the surface model:
- Pre processes the types and methods of the surface model for a better looking output. Same as in [gnostic-grpc](https://github.com/googleapis/gnostic-grpc/blob/b47c208c999b5efd9c159c3055ac55fbc478e9e9/generator/language.go#L114)
- Adjusts the render to the types and methods from the surface model
- Updates the test cases

### CODE REVIEW

File: language.go [hunk 1]
```diff
@@ -18,7 +18,8 @@ import (
 	"strings"
 	"unicode"
 
-	surface "github.com/googleapis/gnostic/surface"
+	gnostic_grpc "github.com/googleapis/gnostic-grpc/generator"
+	surface_v1 "github.com/googleapis/gnostic/surface"
```
Comment (noahdietz) [inline language.go]: is the `_v1` suffix necessary? I would avoid using it if possible.

File: go.mod [hunk 2]
```diff
@@ -2,13 +2,14 @@ module github.com/googleapis/gnostic-go-generator
 
 require (
 	github.com/docopt/docopt-go v0.0.0-20180111231733-ee0de3bc6815
-	github.com/golang/protobuf v1.3.1
-	github.com/googleapis/gnostic v0.3.0
+	github.com/golang/protobuf v1.3.4
+	github.com/googleapis/gnostic v0.4.1
+	github.com/googleapis/gnostic-grpc v0.0.0-20200319064658-b47c208c999b
```
Comment (noahdietz) [inline go.mod:7]: We might want to consider getting `gnostic-grpc` onto semver releases.

File: language.go [hunk 3]
```diff
@@ -65,35 +65,33 @@ func (language *GoLanguageModel) Prepare(model *surface.Model) {
...
 		m.ClientName = m.Name
+		m.ResponsesTypeName = strings.Title(filteredTypeName(m.ResponsesTypeName))
 	}
+	gnostic_grpc.AdjustSurfaceModel(model, inputDocumentType)
 }
 
-func goParameterName(name string) string {
+func goParameterName(originalName string, t string) string {
+	name := gnostic_grpc.CleanName(originalName)
+	if len(name) == 0 {
```
Comment (noahdietz) [inline language.go]: Can we do string comparison here instead of len check? `if name == "" {`

File: language.go [hunk 4]
```diff
@@ -65,35 +65,33 @@ func (language *GoLanguageModel) Prepare(model *surface.Model) {
...
-	name = strings.Replace(name, "-", "_", -1)
-	name = snakeCaseToCamelCaseWithCapitalizedFirstLetter(name)
-	// avoid integers
-	if name == "200" {
-		return "OK"
-	} else if unicode.IsDigit(rune(name[0])) {
-		return "Code" + name
+func goFieldName(name string, t string) string {
+	name = gnostic_grpc.CleanName(name)
+	if len(name) == 0 {
```
Comment (noahdietz) [inline language.go]: Same comment here about string comparison.

File: language.go [hunk 5]
```diff
@@ -65,35 +65,33 @@ func (language *GoLanguageModel) Prepare(model *surface.Model) {
...
+		name = gnostic_grpc.CleanName(t)
 	}
+	name = snakeCaseToCamelCaseWithCapitalizedFirstLetter(name)
```
Comment (noahdietz) [inline language.go]: Inline this with the `return` statement please.

`return snakeCaseToCamelCaseWithCapitalizedFirstLetter(name)`

Side note: I know this method wasn't added in this PR, and no need to change it here, but that name is way too long. `snakeToCamelExported` or `snakeToUpperCamel` (upper camel case aka Pascal Case) are better options in my opinion (assuming the "CapitalizedFirstLetter" part is referring to the exported version of a field name).

File: render_client.go [hunk 6]
```diff
@@ -108,11 +108,11 @@ func (renderer *Renderer) RenderClient() ([]byte, error) {
 		}
 
 		if method.Method == "POST" {
-			f.WriteLine(`body := new(bytes.Buffer)`)
+			f.WriteLine(`reqBody := new(bytes.Buffer)`)
```
Comment (noahdietz) [inline render_client.go]: Nit: I might like the name `payload` better. It's short/one word (like `body`), but implies it's being sent (e.g. as a request body). WDYT?

**Review by noahdietz — COMMENTED** [review]
Generally this looks fine to me, I just wonder what the opportunity for breaking changes is. It seems as though there are significant changes to the _generated surface_ that might break those already using this tool. WDYT?

Also, I'd like @timburks to review as well.

**Comment by LorenzHW** [comment]
Here is a brief summary why this is necessary:
- During GSoC we [reimplemented](https://github.com/googleapis/gnostic/pull/136) the surface model.
- This [PR](https://github.com/googleapis/gnostic-go-generator/pull/14) should have taken care of that, however we lost track of it and closed it eventually.
- Then Tim opened [this](https://github.com/googleapis/gnostic-grpc/issues/11) issue and I realized that the same problem exists for gnostic-go-generator. Basically, the code written for this issue gets called now inside gnostic-go-generator as well.

If I am not entirely mistaken gnostic-go-generator has not been working for v3 input files since the reimplementation of the surface model.

Also, for some weird reason CI did not run (just like in the PR we closed). However, I ran tests locally with no errors. WDYT?

**Comment by noahdietz** [comment]
> If I am not entirely mistaken gnostic-go-generator has not been working for v3 input files since the reimplementation of the surface model.

Ah, makes sense to me.

> Also, for some weird reason CI did not run (just like in the PR we closed).

I just reenabled CI in CircleCi. It _should_ trigger on the next commit (there is no manual trigger capability, boo!).

File: language.go (hunk 1 above)
Comment (timburks) [reply language.go]: I may have introduced that pattern somewhere else, but agree with @noahdietz here, "surface" seems fine.

**Review by timburks — APPROVED** [review]
Thanks for updating this! The generated client looks much better.

File: language.go (hunk 1 above)
Comment (LorenzHW) [reply language.go]: Done

File: language.go (hunk 3 above)
Comment (LorenzHW) [reply language.go]: Done

File: language.go (hunk 4 above)
Comment (LorenzHW) [reply language.go]: Done

File: language.go (hunk 5 above)
Comment (LorenzHW) [reply language.go]: Done

File: render_client.go (hunk 6 above)
Comment (LorenzHW) [reply render_client.go]: Done.

As a side note (because I was initially confused as well why I changed it to `reqBody`): [Here](https://github.com/googleapis/gnostic-go-generator/pull/16/files#diff-5d6b92364de5edfd9f7f8caf8fbe11b8R137) we declare a `body` variable again (this time the response body). Therefore it would not generate valid Go code if we would use `body` for the request body as well.

**Review by noahdietz — APPROVED** [review]
Thanks @LorenzHW
